language: node_js

node_js:
- '12'

script:
- npm run lint
- npm run test
- npm run build

notifications:
    email: false

cache:
    directories:
    - node_modules

before_install: 
  - npm @angular/cli analytics off

after_success:
- npm run codecov

